# cloudbuild.yaml
steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "auth",
        "activate-service-account",
        "ndi-tap@ndi-tap-322908.iam.gserviceaccount.com",
        "--key-file=./serviceaccount.json",
        "--project=ndi-tap-322908",
      ]

    # build & push the container image
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      [
        "--cache=true",
        "--cache-ttl=48h",
        "--destination=gcr.io/ndi-tap-322908/todo:latest",
      ]

    # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "todo",
        "--image",
        "gcr.io/ndi-tap-322908/todo:latest",
        "--region",
        "asia-southeast1",
        "--allow-unauthenticated",
        "--platform",
        "managed",
      ]
